name: workflow scope varaible

on:
  workflow_dispatch:
    inputs: 
      number1:
        description: First Number
        default: 0
        required: true
      number2:
        description: Second Number
        default: 0
        required: true
      

env:
  cloud: Azure_Cloud platform
jobs:
  greeting_job:
    runs-on: ubuntu-latest
    env:
      Greetings: Warm Good Evening
    steps:
      - name: "Say Hello to Ashish it's Monday"
        run: echo "$Greetings, $First_name is $cloud!"
        env:
          First_name: Rushikesh
      - name: "Context Variable's is defined in this step"
        run: | 
          echo "Name of the Repository ${{github.repository}}"
          echo "Name of the workflow: ${{github.workflow}}"
          echo "Name of the triggering actor: ${{github.triggering_actor}}"
  Adding_Input_Numbers:
    runs-on: ubuntu-latest
    steps:
      - name: Adding numbers
        id: sum
        run: |
          Result=$((${{inputs.number1}} + ${{inputs.number2}} ))"
          echo "sum=$Result" >> $GITHUB_OUTPUT
      - name: Display Sum
        run: echo "The sum of two number is, ${{ inputs.number1 }} and ${{inputs.number2}} is ${{steps.sum.outputs.sum}} "
      
