name: workflow scope varaible

on:
  workflow_dispatch

env:
  cloud: Azure_Cloud platform
jobs:
  greeting_job:
    runs-on: ubuntu-latest
    env:
      Greetings: Warm Good Evening
    steps:
      - name: "Say Hello to Ashish it's Monday"
        run: echo "$Greetings, $First_name is $cloud!"
        env:
          First_name: Rushikesh
      - name: "Context Variable's is defined in this step"
        run: | 
          echo: "Name of the Repository ${{github.repository}}"
          echo: "Name of the workflow: ${{github.workflow}}"
          echo: "Name of the triggering actor: ${{github.triggering_actor}}"
    
